---
version: "3.9"

services:

  server:
    <<: &local_volumes
      volumes:
        - ./server/:/code/server
        - ./data/docker:/data
    command: ["uvicorn", "server.app.main:app", "--reload", "--host", "0.0.0.0"]
    ports:
      - "8888:8000"

  hub:
    <<: *local_volumes