---
version: "3.9"
services:

  server:
    <<: &server_pi
      image: ghcr.io/damienallen/growbot-server:pi
      build:
        target: dev
        cache_from:
          - ghcr.io/damienallen/growbot-server:pi
      volumes:
        - ./server/:/code/server
        - ./data:/data
    ports:
      - "4242:8000"

  hub:
    <<: *server_pi
