---
version: "3.9"
services:
  server:
    <<: &server_base
      image: ghcr.io/damienallen/growbot-server:main
      build:
        context: ./server
        cache_from:
          - ghcr.io/damienallen/growbot-server:main
        target: dev
      restart: unless-stopped
      env_file: ./config/.env
      command: ["uvicorn", "server.app.main:app", "--host", "0.0.0.0"]
      volumes:
      - ./config/ssh:/ssh_keys/
      - ./config/ssh/known_hosts:/root/.ssh/known_hosts
      depends_on:
      - mqtt_broker
      networks:
        - localnet
    environment:
      - FASTAPI=true

  db:
    image: influxdb:2.7.0
    restart: always
    env_file: ./config/.env
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - localnet

  hub:
    <<: *server_base
    command: ["python", "-m", "server.hub.mqtt"]

  mqtt_broker:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - localnet
    ports:
      - 1883:1883
      - 9001:9001

networks:
  localnet:

volumes:
  influxdb_data: