---
version: "3.9"
services:

  server:
    <<: &server_pi
      build:
        target: prod
      volumes:
        - /home/pi/data:/data
        - /home/pi/captures:/captures
    ports:
      - "4242:8000"

  hub:
    <<: *server_pi
