[tool.poetry]
name = "growbot"
version = "0.1.0"
description = ""
authors = ["Damien Allen <dev@dallen.co>"]

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^8.0.1"
font-fredoka-one = "^0.0.4"
inky = "^1.1.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
