[tool.poetry]
name = "growbot-ctrl"
version = "1.0.0"
description = "PiZero environmental control"
authors = ["Damien Allen <dev@dallen.co>"]

[tool.poetry.dependencies]
python = "^3.10"
gpiozero = "^1.6.2"

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
